In [1]:
import re

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import pairwise_distances

In [2]:
def get_weighted_costs(file_paths):
    costs = []
    for index, cost_path in enumerate(file_paths):
        dataset, algorithm, k = re.findall(r"/.+/(.+)/(.+)-k(\d+)-", str(cost_path))[0]
        with open(cost_path, "r") as f:
            weighted_cost = float(f.read())
        costs.append({
            "dataset": dataset,
            "algorithm": algorithm,
            "k": k,
            "cost": weighted_cost,
            "file_path": str(cost_path)
        })
    return pd.DataFrame(costs)

In [3]:
# data_results_dir = Path("../data/results/tower/")
data_results_dir = Path("../data/results/covertype/")
# data_results_dir = Path("../data/results/census/")

In [4]:
cost_paths = list(data_results_dir.glob("**/real_cost.txt"))

In [5]:
len(cost_paths)

246

In [6]:
df_cost_data = get_weighted_costs(cost_paths)

In [7]:
df_aggr_cost_data = df_cost_data.groupby(["dataset", "algorithm", "k"], as_index=False).agg(
    cost_count=("cost", "count"),
    cost_mean=("cost", "mean"),
    cost_std=("cost", "std")
)
df_aggr_cost_data

,dataset,algorithm,k,cost_count,cost_mean,cost_std
0,covertype,bico,10,17,3.403564e+11,8.802695e+08
1,covertype,bico,20,17,2.047561e+11,8.510785e+08
2,covertype,bico,30,17,1.555837e+11,7.019566e+08
3,covertype,bico,40,17,1.297791e+11,5.480104e+08
4,covertype,bico,50,17,1.137582e+11,4.555466e+08
5,covertype,group-sampling,10,17,3.415869e+11,1.078958e+09
6,covertype,group-sampling,20,16,2.055935e+11,1.221846e+09
7,covertype,group-sampling,30,16,1.556877e+11,8.543948e+08
8,covertype,group-sampling,40,16,1.303204e+11,7.256397e+08
9,covertype,group-sampling,50,16,1.142005e+11,4.149013e+08
10,covertype,sensitivity-sampling,10,16,3.419419e+11,9.509502e+08
11,covertype,sensitivity-sampling,20,16,2.057139e+11,9.665341e+08
12,covertype,sensitivity-sampling,30,16,1.568697e+11,1.038072e+09
13,covertype,sensitivity-sampling,40,16,1.306866e+11,5.900194e+08
14,covertype,sensitivity-sampling,50,16,1.144453e+11,4.834973e+08

In [8]:
df = pd.pivot_table(df_aggr_cost_data, values="cost_mean", index=["algorithm"], columns=["k"])
df.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)

In [9]:
df = pd.pivot_table(df_aggr_cost_data, values="cost_std", index=["algorithm"], columns=["k"])
df.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)