In [1]:
import re

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import pairwise_distances

In [2]:
def get_weighted_costs(file_paths):
    costs = []
    for index, cost_path in enumerate(file_paths):
        dataset, algorithm, k = re.findall(r"/.+/(.+)/(.+)-k(\d+)-", str(cost_path))[0]
        with open(cost_path, "r") as f:
            weighted_cost = float(f.read())
        costs.append({
            "dataset": dataset,
            "algorithm": algorithm,
            "k": k,
            "cost": weighted_cost,
            "file_path": str(cost_path)
        })
    return pd.DataFrame(costs)

In [3]:
# data_results_dir = Path("../data/results/experiments/tower/")
# data_results_dir = Path("../data/results/experiments/covertype/")
data_results_dir = Path("../data/results/experiments/census/")

In [4]:
cost_paths = list(data_results_dir.glob("**/real_cost.txt"))

In [5]:
len(cost_paths)

300

In [6]:
df_cost_data = get_weighted_costs(cost_paths)

In [7]:
df_aggr_cost_data = df_cost_data.groupby(["dataset", "algorithm", "k"], as_index=False).agg(
    cost_count=("cost", "count"),
    cost_mean=("cost", "mean"),
    cost_std=("cost", "std")
)
df_aggr_cost_data

   dataset             algorithm   k  cost_count     cost_mean      cost_std
0   census                  bico  10          20  2.492300e+08  5.058462e+06
1   census                  bico  20          20  1.896409e+08  2.446615e+06
2   census                  bico  30          20  1.595369e+08  1.989445e+06
3   census                  bico  40          20  1.413742e+08  1.826215e+06
4   census                  bico  50          20  1.289143e+08  1.138627e+06
5   census        group-sampling  10          20  2.473318e+08  5.512936e+06
6   census        group-sampling  20          20  1.908562e+08  3.447474e+06
7   census        group-sampling  30          20  1.600878e+08  2.174087e+06
8   census        group-sampling  40          20  1.408244e+08  2.008869e+06
9   census        group-sampling  50          20  1.293495e+08  1.457231e+06
10  census  sensitivity-sampling  10          20  2.491597e+08  7.445979e+06
11  census  sensitivity-sampling  20          20  1.909931e+08  3.268594e+06
12  census  sensitivity-sampling  30          20  1.615374e+08  2.930217e+06
13  census  sensitivity-sampling  40          20  1.413584e+08  2.134717e+06
14  census  sensitivity-sampling  50          20  1.293509e+08  1.658116e+06

In [8]:
df = pd.pivot_table(df_aggr_cost_data, values="cost_mean", index=["algorithm"], columns=["k"])
df#.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)

In [9]:
df = pd.pivot_table(df_aggr_cost_data, values="cost_std", index=["algorithm"], columns=["k"])
df#.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)