In [22]:
import re

from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import pairwise_distances

In [23]:
def get_weighted_costs(file_paths):
    costs = []
    for index, cost_path in enumerate(file_paths):
        dataset, algorithm, k = re.findall(r"/.+/(.+)/(.+)-k(\d+)-", str(cost_path))[0]
        with open(cost_path, "r") as f:
            weighted_cost = float(f.read())
        costs.append({
            "dataset": dataset,
            "algorithm": algorithm,
            "k": k,
            "cost": weighted_cost,
            "file_path": str(cost_path)
        })
    return pd.DataFrame(costs)

In [24]:
data_results_dir = Path("../data/results/hardinstance/")

## Real Costs

In [25]:
real_cost_paths = list(data_results_dir.glob("**/real_cost.txt"))

In [26]:
len(real_cost_paths)

111

In [27]:
df_real_costs = get_weighted_costs(real_cost_paths)

In [28]:
df_aggr_real_cost_data = df_real_costs.groupby(["dataset", "algorithm", "k"], as_index=False).agg(
    cost_count=("cost", "count"),
    cost_mean=("cost", "mean"),
    cost_std=("cost", "std")
)
df_aggr_real_cost_data

,dataset,algorithm,k,cost_count,cost_mean,cost_std
0,hardinstance,bico,10,10,4.852765e+06,49864.529677
1,hardinstance,bico,20,10,1.331775e+07,107411.321838
2,hardinstance,bico,30,10,2.596250e+06,15255.984079
3,hardinstance,bico,40,10,8.240570e+06,67835.103465
4,hardinstance,bico,50,10,2.024525e+07,149615.975928
5,hardinstance,group-sampling,10,8,4.639371e+06,59324.589029
6,hardinstance,group-sampling,20,8,1.285667e+07,242183.267664
7,hardinstance,group-sampling,30,8,2.542662e+06,33421.397631
8,hardinstance,group-sampling,40,7,8.143744e+06,58082.613830
9,hardinstance,group-sampling,50,1,1.987075e+07,NaN
10,hardinstance,sensitivity-sampling,10,8,4.672991e+06,34843.119526
11,hardinstance,sensitivity-sampling,20,7,1.288524e+07,142236.564482
12,hardinstance,sensitivity-sampling,30,7,2.564847e+06,31395.382620
13,hardinstance,sensitivity-sampling,40,6,8.263263e+06,54791.375166
14,hardinstance,sensitivity-sampling,50,1,2.013685e+07,NaN

### Real cost summary

In [29]:
df_real_cost_summary = pd.pivot_table(df_aggr_real_cost_data, values="cost_mean", index=["algorithm"], columns=["k"])
df_real_cost_summary#.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)

k,10,20,30,40,50
algorithm,,,,,
bico,4.852765e+06,1.331775e+07,2.596250e+06,8.240570e+06,2.024525e+07
group-sampling,4.639371e+06,1.285667e+07,2.542662e+06,8.143744e+06,1.987075e+07
sensitivity-sampling,4.672991e+06,1.288524e+07,2.564847e+06,8.263263e+06,2.013685e+07

### Real cost variances

In [30]:
df_real_cost_summary_std = pd.pivot_table(df_aggr_real_cost_data, values="cost_std", index=["algorithm"], columns=["k"])
df_real_cost_summary_std#.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)

k,10,20,30,40,50
algorithm,,,,,
bico,49864.529677,107411.321838,15255.984079,67835.103465,149615.975928
group-sampling,59324.589029,242183.267664,33421.397631,58082.613830,NaN
sensitivity-sampling,34843.119526,142236.564482,31395.382620,54791.375166,NaN

## Coreset Costs

In [15]:
coreset_cost_paths = list(data_results_dir.glob("**/coreset_cost.txt"))

In [16]:
len(coreset_cost_paths)

112

In [17]:
df_coreset_costs = get_weighted_costs(coreset_cost_paths)

In [18]:
df_aggr_coreset_cost_data = df_coreset_costs.groupby(["dataset", "algorithm", "k"], as_index=False).agg(
    cost_count=("cost", "count"),
    cost_mean=("cost", "mean"),
    cost_std=("cost", "std")
)
df_aggr_coreset_cost_data

,dataset,algorithm,k,cost_count,cost_mean,cost_std
0,hardinstance,bico,10,11,1.246969e+06,75630.705419
1,hardinstance,bico,20,10,3.487690e+06,158875.602430
2,hardinstance,bico,30,10,7.955912e+05,30478.274584
3,hardinstance,bico,40,10,2.038664e+06,123529.183592
4,hardinstance,bico,50,10,4.722689e+06,334296.891985
5,hardinstance,group-sampling,10,8,4.587714e+06,56435.294508
6,hardinstance,group-sampling,20,8,1.269058e+07,225976.772754
7,hardinstance,group-sampling,30,8,2.511511e+06,31687.153632
8,hardinstance,group-sampling,40,7,8.044408e+06,53043.887031
9,hardinstance,group-sampling,50,1,1.963607e+07,NaN
10,hardinstance,sensitivity-sampling,10,8,4.653270e+06,31990.582913
11,hardinstance,sensitivity-sampling,20,7,1.282170e+07,136810.584088
12,hardinstance,sensitivity-sampling,30,7,2.552491e+06,30003.380505
13,hardinstance,sensitivity-sampling,40,6,8.230189e+06,54088.540931
14,hardinstance,sensitivity-sampling,50,1,2.004903e+07,NaN

In [20]:
df_coreset_cost_summary = pd.pivot_table(df_aggr_coreset_cost_data, values="cost_mean", index=["algorithm"], columns=["k"])
df_coreset_cost_summary

k,10,20,30,40,50
algorithm,,,,,
bico,1.246969e+06,3.487690e+06,7.955912e+05,2.038664e+06,4.722689e+06
group-sampling,4.587714e+06,1.269058e+07,2.511511e+06,8.044408e+06,1.963607e+07
sensitivity-sampling,4.653270e+06,1.282170e+07,2.552491e+06,8.230189e+06,2.004903e+07

In [31]:
df_coreset_cost_summary_std = pd.pivot_table(df_aggr_coreset_cost_data, values="cost_std", index=["algorithm"], columns=["k"])
df_coreset_cost_summary_std#.style.format(precision=0, thousands=",").highlight_min(color = 'lightgreen', axis = 0)

k,10,20,30,40,50
algorithm,,,,,
bico,75630.705419,158875.602430,30478.274584,123529.183592,334296.891985
group-sampling,56435.294508,225976.772754,31687.153632,53043.887031,NaN
sensitivity-sampling,31990.582913,136810.584088,30003.380505,54088.540931,NaN

## Distortion

In [32]:
df_real_cost_summary / df_coreset_cost_summary

k                           10        20        30        40        50
algorithm
bico                  3.891648  3.818501  3.263296  4.042143  4.286806
group-sampling        1.011260  1.013088  1.012403  1.012349  1.011952
sensitivity-sampling  1.004238  1.004956  1.004841  1.004019  1.004380